version: '3.1'
services:
  WEB:
    image: nginx:1.25-alpine3.18-perl
    env_file:
      - .env
    restart: always
    depends_on:
      - php
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    # - ./junior-devops-spetsialist/src:/var/www/laravel
    links:
      - php
    ports:
      - "80:80"
    networks:
      appweb:

  php:
    build:
      context: . 
      dockerfile: dockerfile/phpapp.dockerfile
    # env_file:
    #   - .env
    depends_on:
      - writer_db
    # volumes:
      # - ./.env:/var/www/laravel/.env
      # - ./junior-devops-spetsialist/src:/var/www/laravel
    networks:
      appweb:
    #     ipv4_address: 172.20.0.15
    # ports:
    #   - "9001:9000"

  writer_db:
    image: mysql
    env_file:
      - .env
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_HOST: "localhost"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      appweb:
        ipv4_address: 172.20.0.10
    volumes:
      - ./mysql/master.cnf:/etc/my.cnf
      - ./mysql/master.sql:/docker-entrypoint-initdb.d/start.sql      
    ports:
      - "3306:3306"

  reader_db:
    image: mysql
    env_file:
      - .env
    depends_on:
      - WEB
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_HOST: "localhost"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      # MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      appweb:
        ipv4_address: 172.20.0.11
    volumes:
      - ./mysql/slave.cnf:/etc/my.cnf
      - ./mysql/slave.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - "3307:3306"

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 9111:80
  #   environment:
  #     - PMA_ARBITRARY=1

networks:
  appweb:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24